---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simplevis-web
  namespace: simplevis
spec:
  to:
    kind: Service
    name: simplevis-service
    weight: 100
  port:
    targetPort: 8000
  wildcardPolicy: None
