---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-simplevis
  namespace: simplevis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: thin
