---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: simplevis-pretrained-deployment
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '1'
  namespace: simplevis
  labels:
    app: simplevis-pretrained
    app.openshift.io/runtime-namespace: simplevis
spec:
  restartPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: simplevis-pretrained
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplevis-pretrained
        deploymentconfig: simplevis-pretrained
    spec:
      containers:
        - name: simplevis-pretrained
          image: nexus.davenet.local:8080/simplevis/simplevis:pretrained
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/app-root/src/simplevis-data
              name: simplevis-data
          resources: {}
          env:
            - name: ENVIRONMENT_NAME
              value: "OpenShift"
            - name: SIMPLEVIS_DATA
              value: /opt/app-root/src/simplevis-data
      volumes:
        - name: simplevis-data
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
